name: Deploy Demo Website

on:
  push:
    branches:
      - vite

jobs:
  vite-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Website
        run: yarn build

  deploy:
    needs: vite-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn bootstrap

      - name: Build Website
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website
          GIT_CONFIG_NAME: pengxiaotian
          GIT_CONFIG_EMAIL: 673923162@qq.com
          COMMIT_MESSAGE: website deploy
